### ISSUE TITLE
Error when requesting an extract from a non-unlocked municipality 

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#10]
```
2019-08-10 05:50:55.100 DEBUG 60777 --- [nio-8080-exec-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL query
2019-08-10 05:50:55.100 DEBUG 60777 --- [nio-8080-exec-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [SELECT basedatadate from live.oerb_xtnx_v1_0annex_municipalitywithplrc WHERE municipality=?]
2019-08-10 05:50:55.100 DEBUG 60777 --- [nio-8080-exec-1] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-08-10 05:50:55.106 DEBUG 60777 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Failed to complete request: org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
2019-08-10 05:50:55.107 ERROR 60777 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0] with root cause

org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
        at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:97) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:783) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:808) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at ch.ehi.oereb.webservice.OerebController.getBasedatadateOfMunicipality(OerebController.java:1193) ~[main/:na]
        at ch.ehi.oereb.webservice.OerebController.setBaseData(OerebController.java:501) ~[main/:na]
        at ch.ehi.oereb.webservice.OerebController.createExtract(OerebController.java:423) ~[main/:na]
        at ch.ehi.oereb.webservice.OerebController.getExtractWithGeometryByEgrid(OerebController.java:281) ~[main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]```

**Comment by claeis** [comment]
returns http status 204
